site_name: Controlled Experimentation of Model Search Behaviour with Geniie-Lab
nav:
  - Home: index.md
  - Hands-on:
    - handson/index.md
    - Prerequisites:
      - handson/prerequisites/dataset.md
      - Indexing:
        - handson/prerequisites/indexing.md
        - handson/prerequisites/indexing_bm25.md
        - handson/prerequisites/indexing_splade.md
        - handson/prerequisites/indexing_dpr.md
      - handson/prerequisites/llms.md
    - How to Prepare: handson/howto_prepare/index.md
    - Experimental Settings: handson/experimental_settings/index.md
  - About: about.md
theme:
  name: material
  language: en
  palette:
    scheme: default
    primary: black
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.top
  custom_dir: overrides
  icon:
    logo: material/alpha-g-box
plugins:
  - search:
      enabled: false
markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://geniie-lab.github.io/chiir2026/
copyright: Copyright &copy; 2026 Hideo Joho. All rights reserved.

